#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AbilityDeco_teleporter

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass AbilityDeco_teleporter.AbilityDeco_teleporter_C
// 0x0000 (0x0640 - 0x0640)
class AAbilityDeco_teleporter_C final : public AFortAbilityDecoTool
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityDeco_teleporter_C">();
	}
	static class AAbilityDeco_teleporter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAbilityDeco_teleporter_C>();
	}
};
static_assert(alignof(AAbilityDeco_teleporter_C) == 0x000004, "Wrong alignment on AAbilityDeco_teleporter_C");
static_assert(sizeof(AAbilityDeco_teleporter_C) == 0x000640, "Wrong size on AAbilityDeco_teleporter_C");

}

#pragma pack(pop)
