#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIGoalManager

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass AIGoalManager.AIGoalManager_C
// 0x0004 (0x0318 - 0x0314)
class AAIGoalManager_C final : public AFortAIGoalManager
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0314(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIGoalManager_C">();
	}
	static class AAIGoalManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAIGoalManager_C>();
	}
};
static_assert(alignof(AAIGoalManager_C) == 0x000004, "Wrong alignment on AAIGoalManager_C");
static_assert(sizeof(AAIGoalManager_C) == 0x000318, "Wrong size on AAIGoalManager_C");
static_assert(offsetof(AAIGoalManager_C, DefaultSceneRoot) == 0x000314, "Member 'AAIGoalManager_C::DefaultSceneRoot' has a wrong offset!");

}

#pragma pack(pop)
