#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_AdrenalineRush

#include "Basic.hpp"

#include "B_Prj_AdrenalineRush_classes.hpp"
#include "B_Prj_AdrenalineRush_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function B_Prj_AdrenalineRush.B_Prj_AdrenalineRush_C.ExecuteUbergraph_B_Prj_AdrenalineRush
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Prj_AdrenalineRush_C::ExecuteUbergraph_B_Prj_AdrenalineRush(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_AdrenalineRush_C", "ExecuteUbergraph_B_Prj_AdrenalineRush");

	Params::B_Prj_AdrenalineRush_C_ExecuteUbergraph_B_Prj_AdrenalineRush Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Prj_AdrenalineRush.B_Prj_AdrenalineRush_C.PassInfo
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Radius                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AFortPlayerPawn*                  Owner_0                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Level                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Prj_AdrenalineRush_C::PassInfo(float Radius, class AFortPlayerPawn* Owner_0, int32 Level)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_AdrenalineRush_C", "PassInfo");

	Params::B_Prj_AdrenalineRush_C_PassInfo Parms{};

	Parms.Radius = Radius;
	Parms.Owner_0 = Owner_0;
	Parms.Level = Level;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Prj_AdrenalineRush.B_Prj_AdrenalineRush_C.PP Shockwave__UpdateFunc
// (BlueprintEvent)

void AB_Prj_AdrenalineRush_C::PP_Shockwave__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_AdrenalineRush_C", "PP Shockwave__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Prj_AdrenalineRush.B_Prj_AdrenalineRush_C.PP Shockwave__FinishedFunc
// (BlueprintEvent)

void AB_Prj_AdrenalineRush_C::PP_Shockwave__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_AdrenalineRush_C", "PP Shockwave__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Prj_AdrenalineRush.B_Prj_AdrenalineRush_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_Prj_AdrenalineRush_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_AdrenalineRush_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Prj_AdrenalineRush.B_Prj_AdrenalineRush_C.DestroyPP
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Prj_AdrenalineRush_C::DestroyPP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_AdrenalineRush_C", "DestroyPP");

	UObject::ProcessEvent(Func, nullptr);
}

}

#pragma pack(pop)
