#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_AlwaysSuccess

#include "Basic.hpp"

#include "BTTask_AlwaysSuccess_classes.hpp"
#include "BTTask_AlwaysSuccess_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function BTTask_AlwaysSuccess.BTTask_AlwaysSuccess_C.ExecuteUbergraph_BTTask_AlwaysSuccess
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBTTask_AlwaysSuccess_C::ExecuteUbergraph_BTTask_AlwaysSuccess(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_AlwaysSuccess_C", "ExecuteUbergraph_BTTask_AlwaysSuccess");

	Params::BTTask_AlwaysSuccess_C_ExecuteUbergraph_BTTask_AlwaysSuccess Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_AlwaysSuccess.BTTask_AlwaysSuccess_C.ReceiveExecute
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBTTask_AlwaysSuccess_C::ReceiveExecute(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_AlwaysSuccess_C", "ReceiveExecute");

	Params::BTTask_AlwaysSuccess_C_ReceiveExecute Parms{};

	Parms.OwnerActor = OwnerActor;

	UObject::ProcessEvent(Func, &Parms);
}

}

#pragma pack(pop)
