#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BuildingTooltip

#include "Basic.hpp"

#include "BuildingTooltip_classes.hpp"
#include "BuildingTooltip_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function BuildingTooltip.BuildingTooltip_C.ExecuteUbergraph_BuildingTooltip
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBuildingTooltip_C::ExecuteUbergraph_BuildingTooltip(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BuildingTooltip_C", "ExecuteUbergraph_BuildingTooltip");

	Params::BuildingTooltip_C_ExecuteUbergraph_BuildingTooltip Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BuildingTooltip.BuildingTooltip_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBuildingTooltip_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BuildingTooltip_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BuildingTooltip.BuildingTooltip_C.Set Visible
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    In_Visible                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBuildingTooltip_C::Set_Visible(bool In_Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BuildingTooltip_C", "Set Visible");

	Params::BuildingTooltip_C_Set_Visible Parms{};

	Parms.In_Visible = In_Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BuildingTooltip.BuildingTooltip_C.GetGadget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UHomeBaseBuilding*                Building                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UFortItemDefinition*              ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

class UFortItemDefinition* UBuildingTooltip_C::GetGadget(class UHomeBaseBuilding* Building)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BuildingTooltip_C", "GetGadget");

	Params::BuildingTooltip_C_GetGadget Parms{};

	Parms.Building = Building;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BuildingTooltip.BuildingTooltip_C.SetupTooltip
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    InBuildingTemplateId                                   (Parm, ZeroConstructor)

void UBuildingTooltip_C::SetupTooltip(const class FString& InBuildingTemplateId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BuildingTooltip_C", "SetupTooltip");

	Params::BuildingTooltip_C_SetupTooltip Parms{};

	Parms.InBuildingTemplateId = std::move(InBuildingTemplateId);

	UObject::ProcessEvent(Func, &Parms);
}

}

#pragma pack(pop)
