#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Teleporter

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "GameplayAbilities_structs.hpp"


#pragma pack(push, 0x4)
namespace SDK::Params
{

// Function GA_Teleporter.GA_Teleporter_C.ExecuteUbergraph_GA_Teleporter
// 0x0100 (0x0100 - 0x0000)
struct GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayAbilityActorInfo              CallFunc_GetActorInfo_ReturnValue;                 // 0x0004(0x0034)(ContainsInstancedReference)
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData;               // 0x0040(0x0058)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_AbilityTargetDataFromActor_ReturnValue;   // 0x0098(0x0014)()
	TArray<struct FActiveGameplayEffectHandle>    CallFunc_BP_ApplyGameplayEffectToTarget_ReturnValue; // 0x00AC(0x000C)(ZeroConstructor, ReferenceParm)
	class AActor*                                 CallFunc_GetAvatarActorFromActorInfo_ReturnValue;  // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AFortPawn*                              K2Node_DynamicCast_AsFort_Pawn;                    // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_CommitAbility_ReturnValue;             // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C2[0x2];                                       // 0x00C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortAbilityDecoTool*                   K2Node_DynamicCast_AsFort_Ability_Deco_Tool;       // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess3;                      // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_CommitAbility_ReturnValue2;            // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA[0x2];                                       // 0x00CA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAbilityToolSpawnParameters            CallFunc_GetSpawnParameters_OutSpawnParamters;     // 0x00CC(0x0020)()
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x00EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_ED[0x3];                                       // 0x00ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ABuildingActor*                         CallFunc_AbilitySpawnDeco_ReturnValue;             // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AB_Teleporter_C*                        K2Node_DynamicCast_AsB_Teleporter;                 // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess4;                      // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter) == 0x000004, "Wrong alignment on GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter");
static_assert(sizeof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter) == 0x000100, "Wrong size on GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, EntryPoint) == 0x000000, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_GetActorInfo_ReturnValue) == 0x000004, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_GetActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x000038, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_DynamicCast_bSuccess) == 0x00003C, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_MakeStruct_GameplayEventData) == 0x000040, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_MakeStruct_GameplayEventData' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_AbilityTargetDataFromActor_ReturnValue) == 0x000098, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_AbilityTargetDataFromActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_BP_ApplyGameplayEffectToTarget_ReturnValue) == 0x0000AC, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_BP_ApplyGameplayEffectToTarget_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_GetAvatarActorFromActorInfo_ReturnValue) == 0x0000B8, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_GetAvatarActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_DynamicCast_AsFort_Pawn) == 0x0000BC, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_DynamicCast_AsFort_Pawn' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_DynamicCast_bSuccess2) == 0x0000C0, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_DynamicCast_bSuccess2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_K2_CommitAbility_ReturnValue) == 0x0000C1, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_K2_CommitAbility_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_DynamicCast_AsFort_Ability_Deco_Tool) == 0x0000C4, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_DynamicCast_AsFort_Ability_Deco_Tool' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_DynamicCast_bSuccess3) == 0x0000C8, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_DynamicCast_bSuccess3' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_K2_CommitAbility_ReturnValue2) == 0x0000C9, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_K2_CommitAbility_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_GetSpawnParameters_OutSpawnParamters) == 0x0000CC, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_GetSpawnParameters_OutSpawnParamters' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_HasAuthority_ReturnValue) == 0x0000EC, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_GetController_ReturnValue) == 0x0000F0, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, CallFunc_AbilitySpawnDeco_ReturnValue) == 0x0000F4, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::CallFunc_AbilitySpawnDeco_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_DynamicCast_AsB_Teleporter) == 0x0000F8, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_DynamicCast_AsB_Teleporter' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter, K2Node_DynamicCast_bSuccess4) == 0x0000FC, "Member 'GA_Teleporter_C_ExecuteUbergraph_GA_Teleporter::K2Node_DynamicCast_bSuccess4' has a wrong offset!");

// Function GA_Teleporter.GA_Teleporter_C.DestroyExistingPortalsForPlayer
// 0x0030 (0x0030 - 0x0000)
struct GA_Teleporter_C_DestroyExistingPortalsForPlayer final
{
public:
	class AController*                            Controller;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TArray<class ABuildingGameplayActor*>         CallFunc_GetAllActorsOfClass_OutActors;            // 0x0010(0x000C)(ZeroConstructor, ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ABuildingGameplayActor*                 CallFunc_Array_Get_Item;                           // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetOwningController_ReturnValue;          // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Teleporter_C_DestroyExistingPortalsForPlayer) == 0x000004, "Wrong alignment on GA_Teleporter_C_DestroyExistingPortalsForPlayer");
static_assert(sizeof(GA_Teleporter_C_DestroyExistingPortalsForPlayer) == 0x000030, "Wrong size on GA_Teleporter_C_DestroyExistingPortalsForPlayer");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, Controller) == 0x000000, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::Controller' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, Temp_int_Array_Index_Variable) == 0x000004, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, CallFunc_GetAllActorsOfClass_OutActors) == 0x000010, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, CallFunc_Array_Length_ReturnValue) == 0x00001C, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, CallFunc_Array_Get_Item) == 0x000020, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, CallFunc_Less_IntInt_ReturnValue) == 0x000024, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, CallFunc_GetOwningController_ReturnValue) == 0x000028, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::CallFunc_GetOwningController_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_DestroyExistingPortalsForPlayer, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x00002C, "Member 'GA_Teleporter_C_DestroyExistingPortalsForPlayer::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

// Function GA_Teleporter.GA_Teleporter_C.InitPortalAndSpawnTargetTeleporter
// 0x00E0 (0x00E0 - 0x0000)
struct GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter final
{
public:
	class AB_Teleporter_C*                        NewTeleporter;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FLinearColor                           CallFunc_Array_Get_Item;                           // 0x000C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Array_Get_Item2;                          // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Array_Get_Item3;                          // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UAbilitySystemComponent*                CallFunc_GetAbilitySystemComponent_ReturnValue;    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetFloatAttributeFromAbilitySystemComponent_bSuccessfullyFoundAttribute; // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetFloatAttributeFromAbilitySystemComponent_ReturnValue; // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AFortPlayerController*                  K2Node_DynamicCast_AsFort_Player_Controller;       // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0xF];                                       // 0x0041(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetSecondTeleporterSpawnLoc_SpawnTransform; // 0x0050(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0080(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x008C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0098(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FAbilityToolSpawnParameters            K2Node_MakeStruct_AbilityToolSpawnParameters;      // 0x00A4(0x0020)()
	class ABuildingActor*                         CallFunc_AbilitySpawnDeco_ReturnValue;             // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AB_Teleporter_C*                        K2Node_DynamicCast_AsB_Teleporter;                 // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CD[0x3];                                       // 0x00CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TeleporterLevel;                                   // 0x00D0(0x0004)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor)
	class AB_Teleporter_C*                        TeleporterB;                                       // 0x00D4(0x0004)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor)
	class AB_Teleporter_C*                        TeleporterA;                                       // 0x00D8(0x0004)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter) == 0x000010, "Wrong alignment on GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter");
static_assert(sizeof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter) == 0x0000E0, "Wrong size on GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, NewTeleporter) == 0x000000, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::NewTeleporter' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_Array_Length_ReturnValue) == 0x000004, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_Percent_IntInt_ReturnValue) == 0x000008, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_Array_Get_Item) == 0x00000C, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_Array_Get_Item2) == 0x00001C, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_Array_Get_Item3) == 0x000020, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_Array_Get_Item3' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_GetAbilitySystemComponent_ReturnValue) == 0x000024, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_GetAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_GetController_ReturnValue) == 0x000028, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_GetFloatAttributeFromAbilitySystemComponent_bSuccessfullyFoundAttribute) == 0x00002C, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_GetFloatAttributeFromAbilitySystemComponent_bSuccessfullyFoundAttribute' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_GetFloatAttributeFromAbilitySystemComponent_ReturnValue) == 0x000030, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_GetFloatAttributeFromAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, K2Node_DynamicCast_AsFort_Player_Controller) == 0x000034, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::K2Node_DynamicCast_AsFort_Player_Controller' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_FTrunc_ReturnValue) == 0x00003C, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, K2Node_SwitchInteger_CmpSuccess) == 0x000040, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_GetSecondTeleporterSpawnLoc_SpawnTransform) == 0x000050, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_GetSecondTeleporterSpawnLoc_SpawnTransform' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_BreakTransform_Location) == 0x000080, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_BreakTransform_Rotation) == 0x00008C, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_BreakTransform_Scale) == 0x000098, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, K2Node_MakeStruct_AbilityToolSpawnParameters) == 0x0000A4, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::K2Node_MakeStruct_AbilityToolSpawnParameters' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, CallFunc_AbilitySpawnDeco_ReturnValue) == 0x0000C4, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::CallFunc_AbilitySpawnDeco_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, K2Node_DynamicCast_AsB_Teleporter) == 0x0000C8, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::K2Node_DynamicCast_AsB_Teleporter' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, K2Node_DynamicCast_bSuccess2) == 0x0000CC, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::K2Node_DynamicCast_bSuccess2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, TeleporterLevel) == 0x0000D0, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::TeleporterLevel' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, TeleporterB) == 0x0000D4, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::TeleporterB' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter, TeleporterA) == 0x0000D8, "Member 'GA_Teleporter_C_InitPortalAndSpawnTargetTeleporter::TeleporterA' has a wrong offset!");

// Function GA_Teleporter.GA_Teleporter_C.GetSecondTeleporterSpawnLoc
// 0x03B0 (0x03B0 - 0x0000)
struct GA_Teleporter_C_GetSecondTeleporterSpawnLoc final
{
public:
	class AActor*                                 FirstTeleporter;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4[0xC];                                        // 0x0004(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             SpawnTransform;                                    // 0x0010(0x0030)(Parm, OutParm, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TArray<struct FRotator>                       K2Node_MakeArray_Array;                            // 0x004C(0x000C)(ZeroConstructor, ReferenceParm)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_64[0xC];                                       // 0x0064(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0070(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x00A0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x00AC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x00B8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00C4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue2;       // 0x00DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakVector_X;                            // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakVector_Y;                            // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakVector_Z;                            // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue3;       // 0x00F4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_BoxTraceSingle_OutHit;                    // 0x0104(0x0080)(ContainsInstancedReference)
	bool                                          CallFunc_BoxTraceSingle_ReturnValue;               // 0x0184(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_185[0x3];                                      // 0x0185(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0188(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0194(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0195(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_196[0x2];                                      // 0x0196(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x019C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01A8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01B4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x01C0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x01CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x01D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x01E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x01F0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue4;       // 0x01FC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_MakeVector_ReturnValue2;                  // 0x0208(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_Array_Get_Item;                           // 0x0214(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_ComposeRotators_ReturnValue;              // 0x0224(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_231[0x3];                                      // 0x0231(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GreaterGreater_VectorRotator_ReturnValue; // 0x0234(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue2;            // 0x0240(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue3;            // 0x024C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_BoxTraceSingle_OutHit2;                   // 0x0258(0x0080)(ContainsInstancedReference)
	bool                                          CallFunc_BoxTraceSingle_ReturnValue2;              // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D9[0x3];                                      // 0x02D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x02DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue2;         // 0x02E0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2EC[0x4];                                      // 0x02EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x02F0(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue5;       // 0x0320(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x032C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue;         // 0x0338(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AActor*                                 LocalFirstTeleporter;                              // 0x0344(0x0004)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor)
	struct FVector                                BoxSweepHalfSize;                                  // 0x0348(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                SweepOffset;                                       // 0x0354(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bFoundGoodSpot;                                    // 0x0360(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_361[0x3];                                      // 0x0361(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FRotator>                       RotationsToTry;                                    // 0x0364(0x000C)(Edit, ZeroConstructor)
	struct FRotator                               RotationToPlayer;                                  // 0x0370(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         SpawnDistance;                                     // 0x037C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
	ETraceTypeQuery                               TraceChannel;                                      // 0x0380(0x0001)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor)
	uint8                                         Pad_381[0x3];                                      // 0x0381(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         SweepIgnoreList;                                   // 0x0384(0x000C)(Edit, ZeroConstructor, DisableEditOnTemplate)
	struct FVector                                StartLoc;                                          // 0x0390(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                EndLoc;                                            // 0x039C(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc) == 0x000010, "Wrong alignment on GA_Teleporter_C_GetSecondTeleporterSpawnLoc");
static_assert(sizeof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc) == 0x0003B0, "Wrong size on GA_Teleporter_C_GetSecondTeleporterSpawnLoc");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, FirstTeleporter) == 0x000000, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::FirstTeleporter' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, SpawnTransform) == 0x000010, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::SpawnTransform' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, Temp_int_Loop_Counter_Variable) == 0x000040, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Add_IntInt_ReturnValue) == 0x000044, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, Temp_int_Array_Index_Variable) == 0x000048, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, K2Node_MakeArray_Array) == 0x00004C, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000058, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_GetTransform_ReturnValue) == 0x000070, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakTransform_Location) == 0x0000A0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakTransform_Rotation) == 0x0000AC, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakTransform_Scale) == 0x0000B8, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000C4, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Add_VectorVector_ReturnValue) == 0x0000D0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Subtract_VectorVector_ReturnValue2) == 0x0000DC, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Subtract_VectorVector_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakVector_X) == 0x0000E8, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakVector_Y) == 0x0000EC, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakVector_Z) == 0x0000F0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Subtract_VectorVector_ReturnValue3) == 0x0000F4, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Subtract_VectorVector_ReturnValue3' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Add_FloatFloat_ReturnValue) == 0x000100, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BoxTraceSingle_OutHit) == 0x000104, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BoxTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BoxTraceSingle_ReturnValue) == 0x000184, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BoxTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_MakeVector_ReturnValue) == 0x000188, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_bBlockingHit) == 0x000194, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_bInitialOverlap) == 0x000195, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_Time) == 0x000198, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_Location) == 0x00019C, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_ImpactPoint) == 0x0001A8, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_Normal) == 0x0001B4, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_ImpactNormal) == 0x0001C0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_PhysMat) == 0x0001CC, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_HitActor) == 0x0001D0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_HitComponent) == 0x0001D4, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_HitBoneName) == 0x0001D8, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_HitItem) == 0x0001E0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_TraceStart) == 0x0001E4, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BreakHitResult_TraceEnd) == 0x0001F0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Subtract_VectorVector_ReturnValue4) == 0x0001FC, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Subtract_VectorVector_ReturnValue4' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_MakeVector_ReturnValue2) == 0x000208, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_MakeVector_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Array_Get_Item) == 0x000214, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Array_Length_ReturnValue) == 0x000220, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_ComposeRotators_ReturnValue) == 0x000224, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_ComposeRotators_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Less_IntInt_ReturnValue) == 0x000230, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_GreaterGreater_VectorRotator_ReturnValue) == 0x000234, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_GreaterGreater_VectorRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Add_VectorVector_ReturnValue2) == 0x000240, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Add_VectorVector_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Add_VectorVector_ReturnValue3) == 0x00024C, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Add_VectorVector_ReturnValue3' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BoxTraceSingle_OutHit2) == 0x000258, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BoxTraceSingle_OutHit2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_BoxTraceSingle_ReturnValue2) == 0x0002D8, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_BoxTraceSingle_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Array_Add_ReturnValue) == 0x0002DC, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_K2_GetActorLocation_ReturnValue2) == 0x0002E0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_K2_GetActorLocation_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_MakeTransform_ReturnValue) == 0x0002F0, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Subtract_VectorVector_ReturnValue5) == 0x000320, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Subtract_VectorVector_ReturnValue5' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Multiply_VectorVector_ReturnValue) == 0x00032C, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, CallFunc_Conv_VectorToRotator_ReturnValue) == 0x000338, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::CallFunc_Conv_VectorToRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, LocalFirstTeleporter) == 0x000344, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::LocalFirstTeleporter' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, BoxSweepHalfSize) == 0x000348, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::BoxSweepHalfSize' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, SweepOffset) == 0x000354, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::SweepOffset' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, bFoundGoodSpot) == 0x000360, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::bFoundGoodSpot' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, RotationsToTry) == 0x000364, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::RotationsToTry' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, RotationToPlayer) == 0x000370, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::RotationToPlayer' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, SpawnDistance) == 0x00037C, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::SpawnDistance' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, TraceChannel) == 0x000380, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::TraceChannel' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, SweepIgnoreList) == 0x000384, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::SweepIgnoreList' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, StartLoc) == 0x000390, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::StartLoc' has a wrong offset!");
static_assert(offsetof(GA_Teleporter_C_GetSecondTeleporterSpawnLoc, EndLoc) == 0x00039C, "Member 'GA_Teleporter_C_GetSecondTeleporterSpawnLoc::EndLoc' has a wrong offset!");

}

#pragma pack(pop)
