#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_HuskLobberRadialMelee

#include "Basic.hpp"

#include "GAB_HuskBaseRadialMelee_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass GAB_HuskLobberRadialMelee.GAB_HuskLobberRadialMelee_C
// 0x0000 (0x06EC - 0x06EC)
class UGAB_HuskLobberRadialMelee_C final : public UGAB_HuskBaseRadialMelee_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_HuskLobberRadialMelee_C">();
	}
	static class UGAB_HuskLobberRadialMelee_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_HuskLobberRadialMelee_C>();
	}
};
static_assert(alignof(UGAB_HuskLobberRadialMelee_C) == 0x000004, "Wrong alignment on UGAB_HuskLobberRadialMelee_C");
static_assert(sizeof(UGAB_HuskLobberRadialMelee_C) == 0x0006EC, "Wrong size on UGAB_HuskLobberRadialMelee_C");

}

#pragma pack(pop)
