#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_NPC_Ice

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass GCN_NPC_Ice.GCN_NPC_Ice_C
// 0x0000 (0x02AC - 0x02AC)
class AGCN_NPC_Ice_C final : public AFortGameplayCueNotify_Looping
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_NPC_Ice_C">();
	}
	static class AGCN_NPC_Ice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_NPC_Ice_C>();
	}
};
static_assert(alignof(AGCN_NPC_Ice_C) == 0x000004, "Wrong alignment on AGCN_NPC_Ice_C");
static_assert(sizeof(AGCN_NPC_Ice_C) == 0x0002AC, "Wrong size on AGCN_NPC_Ice_C");

}

#pragma pack(pop)
