#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Outlander_TriggerHappyCooldown

#include "Basic.hpp"

#include "GET_Cooldown_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass GE_Outlander_TriggerHappyCooldown.GE_Outlander_TriggerHappyCooldown_C
// 0x0000 (0x0368 - 0x0368)
class UGE_Outlander_TriggerHappyCooldown_C final : public UGET_Cooldown_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Outlander_TriggerHappyCooldown_C">();
	}
	static class UGE_Outlander_TriggerHappyCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Outlander_TriggerHappyCooldown_C>();
	}
};
static_assert(alignof(UGE_Outlander_TriggerHappyCooldown_C) == 0x000004, "Wrong alignment on UGE_Outlander_TriggerHappyCooldown_C");
static_assert(sizeof(UGE_Outlander_TriggerHappyCooldown_C) == 0x000368, "Wrong size on UGE_Outlander_TriggerHappyCooldown_C");

}

#pragma pack(pop)
