#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeroInfoLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass HeroInfoLibrary.HeroInfoLibrary_C
// 0x0000 (0x001C - 0x001C)
class UHeroInfoLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static void Get_Core_Stats_By_Hero_ID(const class FString& Hero_ID, const struct FHeroCoreStatSet& UI_Data, class UObject* __WorldContext, TArray<struct FHeroCoreStat>* Data, TArray<float>* Values);
	static void Get_Current_Hero_Core_Stats(class UObject* __WorldContext, TArray<struct FHeroCoreStat>* Data, TArray<float>* Values);
	static void Get_Core_Stat_By_Hero_ID(const class FString& Hero_ID, const struct FGameplayAttribute& Attribute, const struct FHeroCoreStatSet& UI_Data, class UObject* __WorldContext, struct FHeroCoreStat* Stat, float* Value);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HeroInfoLibrary_C">();
	}
	static class UHeroInfoLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHeroInfoLibrary_C>();
	}
};
static_assert(alignof(UHeroInfoLibrary_C) == 0x000004, "Wrong alignment on UHeroInfoLibrary_C");
static_assert(sizeof(UHeroInfoLibrary_C) == 0x00001C, "Wrong size on UHeroInfoLibrary_C");

}

#pragma pack(pop)
