#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HuskVimBlueprint

#include "Basic.hpp"

#include "HuskVimBlueprint_classes.hpp"
#include "HuskVimBlueprint_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function HuskVimBlueprint.HuskVimBlueprint_C.ExecuteUbergraph_HuskVimBlueprint
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHuskVimBlueprint_C::ExecuteUbergraph_HuskVimBlueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "ExecuteUbergraph_HuskVimBlueprint");

	Params::HuskVimBlueprint_C_ExecuteUbergraph_HuskVimBlueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UHuskVimBlueprint_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.AnimNotify_BeehiveDestroyed
// (BlueprintCallable, BlueprintEvent)

void UHuskVimBlueprint_C::AnimNotify_BeehiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "AnimNotify_BeehiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.AnimNotify_SleepingFullyBlended
// (BlueprintCallable, BlueprintEvent)

void UHuskVimBlueprint_C::AnimNotify_SleepingFullyBlended()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "AnimNotify_SleepingFullyBlended");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.AnimNotify_StunnedFullyBlendedState
// (BlueprintCallable, BlueprintEvent)

void UHuskVimBlueprint_C::AnimNotify_StunnedFullyBlendedState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "AnimNotify_StunnedFullyBlendedState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.AnimNotify_StunnedLeftState
// (BlueprintCallable, BlueprintEvent)

void UHuskVimBlueprint_C::AnimNotify_StunnedLeftState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "AnimNotify_StunnedLeftState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByBool_109F76DF4F31F5F29DEB3C9FAF5D09A5
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByBool_109F76DF4F31F5F29DEB3C9FAF5D09A5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByBool_109F76DF4F31F5F29DEB3C9FAF5D09A5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_6735E8134ECB24DD734FB68A0094224B
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_6735E8134ECB24DD734FB68A0094224B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_6735E8134ECB24DD734FB68A0094224B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByInt_73DCE67A4812F862ED8C6780A4006486
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByInt_73DCE67A4812F862ED8C6780A4006486()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByInt_73DCE67A4812F862ED8C6780A4006486");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_487F72FF4CB1C079BB7DB69F6BB3314A
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_487F72FF4CB1C079BB7DB69F6BB3314A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_487F72FF4CB1C079BB7DB69F6BB3314A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_89DB18E44181E92E530A8EB1C2835065
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_89DB18E44181E92E530A8EB1C2835065()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_89DB18E44181E92E530A8EB1C2835065");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_D8B987814BC8214113BE1B9E22F44394
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_D8B987814BC8214113BE1B9E22F44394()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_D8B987814BC8214113BE1B9E22F44394");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_A55CC7A2408CDC13BE5E2E909CDB724C
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_A55CC7A2408CDC13BE5E2E909CDB724C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_A55CC7A2408CDC13BE5E2E909CDB724C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_43BBC9914EAAAC8C994CC4BA6D138971
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_43BBC9914EAAAC8C994CC4BA6D138971()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_43BBC9914EAAAC8C994CC4BA6D138971");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_9BEE9F054AD8E45DBB891E95496CC23A
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_9BEE9F054AD8E45DBB891E95496CC23A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_9BEE9F054AD8E45DBB891E95496CC23A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_61AAFD374F572C1FAC206E9A92B61F32
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_61AAFD374F572C1FAC206E9A92B61F32()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_61AAFD374F572C1FAC206E9A92B61F32");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_97D40CFD4EB5645835403BA4924C0B3E
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_97D40CFD4EB5645835403BA4924C0B3E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_97D40CFD4EB5645835403BA4924C0B3E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_CDBDFCB3423B7A666B668C810913101D
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_CDBDFCB3423B7A666B668C810913101D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_CDBDFCB3423B7A666B668C810913101D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_88EDA46E4106E0FB2B6A9CAAE2C22DF3
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_88EDA46E4106E0FB2B6A9CAAE2C22DF3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_88EDA46E4106E0FB2B6A9CAAE2C22DF3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_440B1F274BAB6915F4A535B80FCB01C7
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_440B1F274BAB6915F4A535B80FCB01C7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_440B1F274BAB6915F4A535B80FCB01C7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_313802304B999C3D178C48BF9DEDEFAE
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_313802304B999C3D178C48BF9DEDEFAE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_313802304B999C3D178C48BF9DEDEFAE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_37EC6B6E4386A12C6F664688A4D188F4
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_37EC6B6E4386A12C6F664688A4D188F4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_37EC6B6E4386A12C6F664688A4D188F4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_73BB9CA046F3F05341252D9489D72103
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_73BB9CA046F3F05341252D9489D72103()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_73BB9CA046F3F05341252D9489D72103");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_7A2A0F6849392A2F649C4FBB52941E96
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_7A2A0F6849392A2F649C4FBB52941E96()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_7A2A0F6849392A2F649C4FBB52941E96");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_80B4C97B4CAC1F2C5D6A56957A7E29B2
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_80B4C97B4CAC1F2C5D6A56957A7E29B2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_80B4C97B4CAC1F2C5D6A56957A7E29B2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_48E307964801AB51DD890898CBE35141
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_48E307964801AB51DD890898CBE35141()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_48E307964801AB51DD890898CBE35141");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_6881341D4EA79B64C4616A9783F931DB
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_6881341D4EA79B64C4616A9783F931DB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_6881341D4EA79B64C4616A9783F931DB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_36293C764E66652AB51D6EA325B93C28
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_36293C764E66652AB51D6EA325B93C28()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_36293C764E66652AB51D6EA325B93C28");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_3E1AAF314A92EA9BAEBDFFA18BFDBE31
// (BlueprintEvent)

void UHuskVimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_3E1AAF314A92EA9BAEBDFFA18BFDBE31()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_3E1AAF314A92EA9BAEBDFFA18BFDBE31");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HuskVimBlueprint.HuskVimBlueprint_C.InitializeHuskType
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortAIPawn*                      InputPin                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHuskVimBlueprint_C::InitializeHuskType(class AFortAIPawn* InputPin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HuskVimBlueprint_C", "InitializeHuskType");

	Params::HuskVimBlueprint_C_InitializeHuskType Parms{};

	Parms.InputPin = InputPin;

	UObject::ProcessEvent(Func, &Parms);
}

}

#pragma pack(pop)
