#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StartForgettingGoal

#include "Basic.hpp"

#include "StartForgettingGoal_classes.hpp"
#include "StartForgettingGoal_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function StartForgettingGoal.StartForgettingGoal_C.ExecuteUbergraph_StartForgettingGoal
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UStartForgettingGoal_C::ExecuteUbergraph_StartForgettingGoal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StartForgettingGoal_C", "ExecuteUbergraph_StartForgettingGoal");

	Params::StartForgettingGoal_C_ExecuteUbergraph_StartForgettingGoal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StartForgettingGoal.StartForgettingGoal_C.ReceiveExecute
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UStartForgettingGoal_C::ReceiveExecute(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StartForgettingGoal_C", "ReceiveExecute");

	Params::StartForgettingGoal_C_ReceiveExecute Parms{};

	Parms.OwnerActor = OwnerActor;

	UObject::ProcessEvent(Func, &Parms);
}

}

#pragma pack(pop)
