#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StartForgettingGoal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// BlueprintGeneratedClass StartForgettingGoal.StartForgettingGoal_C
// 0x0004 (0x0060 - 0x005C)
class UStartForgettingGoal_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x005C(0x0004)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_StartForgettingGoal(int32 EntryPoint);
	void ReceiveExecute(class AActor* OwnerActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StartForgettingGoal_C">();
	}
	static class UStartForgettingGoal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStartForgettingGoal_C>();
	}
};
static_assert(alignof(UStartForgettingGoal_C) == 0x000004, "Wrong alignment on UStartForgettingGoal_C");
static_assert(sizeof(UStartForgettingGoal_C) == 0x000060, "Wrong size on UStartForgettingGoal_C");
static_assert(offsetof(UStartForgettingGoal_C, UberGraphFrame) == 0x00005C, "Member 'UStartForgettingGoal_C::UberGraphFrame' has a wrong offset!");

}

#pragma pack(pop)
