#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: V2_ItemCardFront

#include "Basic.hpp"

#include "V2_ItemCardFront_classes.hpp"
#include "V2_ItemCardFront_parameters.hpp"


#pragma pack(push, 0x4)
namespace SDK
{

// Function V2_ItemCardFront.V2_ItemCardFront_C.ExecuteUbergraph_V2_ItemCardFront
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UV2_ItemCardFront_C::ExecuteUbergraph_V2_ItemCardFront(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("V2_ItemCardFront_C", "ExecuteUbergraph_V2_ItemCardFront");

	Params::V2_ItemCardFront_C_ExecuteUbergraph_V2_ItemCardFront Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function V2_ItemCardFront.V2_ItemCardFront_C.OnFortStoreStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EFortStoreState                         NewStoreState                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UV2_ItemCardFront_C::OnFortStoreStateChanged(EFortStoreState NewStoreState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("V2_ItemCardFront_C", "OnFortStoreStateChanged");

	Params::V2_ItemCardFront_C_OnFortStoreStateChanged Parms{};

	Parms.NewStoreState = NewStoreState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function V2_ItemCardFront.V2_ItemCardFront_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UV2_ItemCardFront_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("V2_ItemCardFront_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function V2_ItemCardFront.V2_ItemCardFront_C.Initialize_Card
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FCard&                     inCard                                                 (Parm)

void UV2_ItemCardFront_C::Initialize_Card(const struct FCard& inCard)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("V2_ItemCardFront_C", "Initialize_Card");

	Params::V2_ItemCardFront_C_Initialize_Card Parms{};

	Parms.inCard = std::move(inCard);

	UObject::ProcessEvent(Func, &Parms);
}


// Function V2_ItemCardFront.V2_ItemCardFront_C.Draw_Card
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UV2_ItemCardFront_C::Draw_Card()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("V2_ItemCardFront_C", "Draw_Card");

	UObject::ProcessEvent(Func, nullptr);
}


// Function V2_ItemCardFront.V2_ItemCardFront_C.Get_CardOverlay_ToolTipWidget_1
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

class UWidget* UV2_ItemCardFront_C::Get_CardOverlay_ToolTipWidget_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("V2_ItemCardFront_C", "Get_CardOverlay_ToolTipWidget_1");

	Params::V2_ItemCardFront_C_Get_CardOverlay_ToolTipWidget_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

#pragma pack(pop)
